### ISSUE TITLE
[Not really an issue] Developing for Pico4 with MRTK2.8 ?

### ISSUE THREAD

**Issue by SashelI** [Phantomxm2021/PicoMRTK3#10]
Hi,

Sorry to bother you with that, but I can't find any information online and you are the closest I can get from a solution : Would it be possible to get PICO4's input with MRTK 2.8 ?

I would need to migrate a project that was made for mrtk devices on the PICO4E, but can't find how. Would you have any leads on that, as you worked on something similar ?

Thanks.

**Comment by Phantomxm2021** [comment]
Not with MRTK2.8. It's only MRTK3.
