### ISSUE TITLE
Controller issue after switching from hand tracking

### ISSUE THREAD

**Issue by aberlaas** [Phantomxm2021/PicoMRTK3#13]
Hi,
Thank you for sharing your PICOMRTK project,

If we start the application by using the controllers, controllers are working fine.
If we start the application by using hand tracking, hand tracking is working fine, but as soon as we switch to using the controllers, nothing happens. 
When this issue occurs, even if we quit the application, the issue remains. We need to restart the PICO device to make the controllers working again.

Any idea on this issue ? Are you experiencing the same behavior ?

Best Regards,

**Comment by Phantomxm2021** [comment]
Which version of Pico OS  / SDK?

We have adapted to the new version of SDK now. You can try it again.
