### ISSUE TITLE
pico Upgrade system 5.7.1 Problems with hand model

### ISSUE THREAD

**Issue by 861172923** [Phantomxm2021/PicoMRTK3#14]

**Comment by liuxunfu** [comment]
**遵循以下步骤处理：**
    1、升级PICO SDK至最新版；
    2、重新配置PICO 手部模型预制件，添加PicoMRTKHandVisualizer脚本后，重新配置手部关节点；
    3、修改PicoMRTKHandVisualizer脚本中更新手部关节点部分代码。
**修改代码部分如下：**
```C#
if (i == (int) HandJoint.JointWrist)
{
      riggedVisualJointsArray[i].localPosition =
                            handJointLocations.jointLocations[i].pose.Position.ToVector3();
      riggedVisualJointsArray[i].localRotation =
                            handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
}
else
{
      //riggedVisualJointsArray[i].localRotation =
      //    handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
      UnityEngine.Pose parentPose = UnityEngine.Pose.identity;
 
      if (i == (int)HandJoint.JointPalm ||
          i == (int)HandJoint.JointThumbMetacarpal ||
          i == (int)HandJoint.JointIndexMetacarpal ||
          i == (int)HandJoint.JointMiddleMetacarpal ||
          i == (int)HandJoint.JointRingMetacarpal ||
          i == (int)HandJoint.JointLittleMetacarpal)
      {
          parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[1].pose.Position.ToVector3(), handJointLocations.jointLocations[1].pose.Orientation.ToQuat());
      }
      else
      {
          parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[i - 1].pose.Position.ToVector3(), handJointLocations.jointLocations[i - 1].pose.Orientation.ToQuat());
      }
 
      var inverseParentRotation = Quaternion.Inverse(parentPose.rotation);
      riggedVisualJointsArray[i].localRotation = inverseParentRotation * handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
}
```

**Comment by TexenJin** [comment]
> 将 PICO SDK 升级到最新版本，重新配置左右切换节点，并修改 PicoMRTKHandVisualizer。
> 
> PicoMRTKHandVisualizer：
> 
> if （i == （int） HandJoint.JointWrist） { riggedVisualJointsArray[i].position = handJointLocations.jointLocations[i].pose.Position.ToVector3（）; riggedVisualJointsArray[i].rotation = handJointLocations.jointLocations[i].pose.Orientation.ToQuat（）; } else { //riggedVisualJointsArray[i].localRotation = // handJointLocations.jointLocations[i].pose.Orientation.ToQuat（）; UnityEngine.Pose parentPose = UnityEngine.Pose.identity;
> 
> ```
>   if (i == (int)HandJoint.JointPalm ||
>       i == (int)HandJoint.JointThumbMetacarpal ||
>       i == (int)HandJoint.JointIndexMetacarpal ||
>       i == (int)HandJoint.JointMiddleMetacarpal ||
>       i == (int)HandJoint.JointRingMetacarpal ||
>       i == (int)HandJoint.JointLittleMetacarpal)
>   {
>       parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[1].pose.Position.ToVector3(), handJointLocations.jointLocations[1].pose.Orientation.ToQuat());
>   }
>   else
>   {
>       parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[i - 1].pose.Position.ToVector3(), handJointLocations.jointLocations[i - 1].pose.Orientation.ToQuat());
>   }
> 
>   var inverseParentRotation = Quaternion.Inverse(parentPose.rotation);
>   riggedVisualJointsArray[i].localRotation = inverseParentRotation * handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
> ```
> 
> }



> 将 PICO SDK 升级到最新版本，重新配置左右切换节点，并修改 PicoMRTKHandVisualizer。
> 
> PicoMRTKHandVisualizer：
> 
> if （i == （int） HandJoint.JointWrist） { riggedVisualJointsArray[i].position = handJointLocations.jointLocations[i].pose.Position.ToVector3（）; riggedVisualJointsArray[i].rotation = handJointLocations.jointLocations[i].pose.Orientation.ToQuat（）; } else { //riggedVisualJointsArray[i].localRotation = // handJointLocations.jointLocations[i].pose.Orientation.ToQuat（）; UnityEngine.Pose parentPose = UnityEngine.Pose.identity;
> 
> ```
>   if (i == (int)HandJoint.JointPalm ||
>       i == (int)HandJoint.JointThumbMetacarpal ||
>       i == (int)HandJoint.JointIndexMetacarpal ||
>       i == (int)HandJoint.JointMiddleMetacarpal ||
>       i == (int)HandJoint.JointRingMetacarpal ||
>       i == (int)HandJoint.JointLittleMetacarpal)
>   {
>       parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[1].pose.Position.ToVector3(), handJointLocations.jointLocations[1].pose.Orientation.ToQuat());
>   }
>   else
>   {
>       parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[i - 1].pose.Position.ToVector3(), handJointLocations.jointLocations[i - 1].pose.Orientation.ToQuat());
>   }
> 
>   var inverseParentRotation = Quaternion.Inverse(parentPose.rotation);
>   riggedVisualJointsArray[i].localRotation = inverseParentRotation * handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
> ```
> 
> }
大哥您能写的规范点吗？

**Comment by TexenJin** [comment]
> Upgrade the PICO SDK to the latest version, reconfigure the left and right hand switch nodes, and modify the PicoMRTKHandVisualizer.
> 
> PicoMRTKHandVisualizer：
> 
> if (i == (int) HandJoint.JointWrist) { riggedVisualJointsArray[i].position = handJointLocations.jointLocations[i].pose.Position.ToVector3(); riggedVisualJointsArray[i].rotation = handJointLocations.jointLocations[i].pose.Orientation.ToQuat(); } else { //riggedVisualJointsArray[i].localRotation = // handJointLocations.jointLocations[i].pose.Orientation.ToQuat(); UnityEngine.Pose parentPose = UnityEngine.Pose.identity;
> 
> ```
>   if (i == (int)HandJoint.JointPalm ||
>       i == (int)HandJoint.JointThumbMetacarpal ||
>       i == (int)HandJoint.JointIndexMetacarpal ||
>       i == (int)HandJoint.JointMiddleMetacarpal ||
>       i == (int)HandJoint.JointRingMetacarpal ||
>       i == (int)HandJoint.JointLittleMetacarpal)
>   {
>       parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[1].pose.Position.ToVector3(), handJointLocations.jointLocations[1].pose.Orientation.ToQuat());
>   }
>   else
>   {
>       parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[i - 1].pose.Position.ToVector3(), handJointLocations.jointLocations[i - 1].pose.Orientation.ToQuat());
>   }
> 
>   var inverseParentRotation = Quaternion.Inverse(parentPose.rotation);
>   riggedVisualJointsArray[i].localRotation = inverseParentRotation * handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
> ```
> 
> }

您好，方便加一下微信吗？我也遇到了同样的问题而且参照您的方案修改后还是行不通

**Comment by liuxunfu** [comment]
> 

qq：1589108908

**Comment by liuxunfu** [comment]
**遵循以下步骤处理：**
    1、升级PICO SDK至最新版；
    2、重新配置PICO 手部模型预制件，添加PicoMRTKHandVisualizer脚本后，重新配置手部关节点；
    3、修改PicoMRTKHandVisualizer脚本中更新手部关节点部分代码。
**修改代码部分如下：**
`if (i == (int) HandJoint.JointWrist)
{
      riggedVisualJointsArray[i].localPosition =
                            handJointLocations.jointLocations[i].pose.Position.ToVector3();
      riggedVisualJointsArray[i].localRotation =
                            handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
}
else
{
      //riggedVisualJointsArray[i].localRotation =
      //    handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
      UnityEngine.Pose parentPose = UnityEngine.Pose.identity;
 
      if (i == (int)HandJoint.JointPalm ||
          i == (int)HandJoint.JointThumbMetacarpal ||
          i == (int)HandJoint.JointIndexMetacarpal ||
          i == (int)HandJoint.JointMiddleMetacarpal ||
          i == (int)HandJoint.JointRingMetacarpal ||
          i == (int)HandJoint.JointLittleMetacarpal)
      {
          parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[1].pose.Position.ToVector3(), handJointLocations.jointLocations[1].pose.Orientation.ToQuat());
      }
      else
      {
          parentPose = new UnityEngine.Pose(handJointLocations.jointLocations[i - 1].pose.Position.ToVector3(), handJointLocations.jointLocations[i - 1].pose.Orientation.ToQuat());
      }
 
      var inverseParentRotation = Quaternion.Inverse(parentPose.rotation);
      riggedVisualJointsArray[i].localRotation = inverseParentRotation * handJointLocations.jointLocations[i].pose.Orientation.ToQuat();
}`

**Comment by Phantomxm2021** [comment]
Thanks. We have adapted to the new version of SDK
