### ISSUE TITLE
手势只能进行Poke操作，无法进行Grab操作

### ISSUE THREAD

**Issue by Kakazito22** [Phantomxm2021/PicoMRTK3#17]
下载工程打包到pico4上后，对场景内的物体只能进行poke操作，无法进行grab操作。
pico系统版本 5.8.0
![image](https://github.com/Phantomxm2021/PicoMRTK3/assets/28171748/2f5368b2-79ca-4164-b6b8-c9f1949c0992)

**Comment by Phantomxm2021** [comment]
Fixed. Use the latest version to solve the problem.
