### ISSUE TITLE
Could not find active control after binding resolution

### ISSUE THREAD

**Issue by zengliangjun** [Phantomxm2021/PicoMRTK3#2]
Configuration could not be retrieved for Microsoft.MixedReality.Toolkit.Accessibility.MRTKAccessibilitySubsystem.
UnityEngine.Debug:LogError (object,UnityEngine.Object)
Microsoft.MixedReality.Toolkit.XRSubsystemHelpers:GetConfiguration<Microsoft.MixedReality.Toolkit.Accessibility.AccessibilitySubsystemConfig, Microsoft.MixedReality.Toolkit.Accessibility.MRTKAccessibilitySubsystem> () (at Packages/com.microsoft.mrtk.core/Utilities/XRSubsystemHelpers.cs:233)
Microsoft.MixedReality.Toolkit.Accessibility.MRTKAccessibilitySubsystem/AccessibilityProvider:.ctor () (at Packages/com.microsoft.mrtk.accessibility/Subsystems/MRTK/MRTKAccessibilitySubsystem.cs:44)
UnityEngine.SubsystemsImplementation.SubsystemDescriptorWithProvider:UnityEngine.ISubsystemDescriptor.Create ()
Microsoft.MixedReality.Toolkit.Subsystems.MRTKLifecycleManager:Awake () (at Packages/com.microsoft.mrtk.core/Subsystems/MRTKLifecycleManager.cs:62)

Could not find active control after binding resolution
UnityEngine.InputSystem.InputManager:OnNativeDeviceDiscovered (int,string)
UnityEngineInternal.Input.NativeInputSystem:NotifyDeviceDiscovered (int,string)

**Comment by Phantomxm2021** [comment]
Please provide more information on this issue. 😀

**Comment by ZhangXiaoyue716** [comment]
请问这个问题您解决了吗？我也报了这个错。

**Comment by Phantomxm2021** [comment]
Add the Configuration profile via Project Settings->MRTK3 for every platform.

**Comment by 2946242422** [comment]
请问解决了吗，我也是这个错误
