### ISSUE TITLE
关于手势追踪的模型方位不正常

### ISSUE THREAD

**Issue by whyqiliao** [Phantomxm2021/PicoMRTK3#3]
如图所示，手势追踪的需要手动设置MRTK RightHand Controller和MRTK LeftHand Controller 里面ArticulatedHandController脚本的ModelParent属性为场景中的CameraOffset，否则在运行时的手部会以手柄作为ModelParent导致手的模型位置不正常偏移
![image](https://user-images.githubusercontent.com/23431123/211815585-09491390-734f-4df2-9bde-12aa16bcc5ea.png)

**Comment by Phantomxm2021** [comment]
Thank you.😀

**Comment by RongxuanMu** [comment]
PLEASE ADD THIS TO THE RIG PREFAB IN THE NEXT UPDATE!!! IT WILL SAVE A LOT OF TIME! (T_T)
请把这个加到下一次更新的 XR Rig Prefab 吧，我在这里浪费了很多时间(T_T)
