### ISSUE TITLE
PICO SDK version restriction

### ISSUE THREAD

**Issue by RongxuanMu** [Phantomxm2021/PicoMRTK3#7]
I noticed the PICO SDK package was labeled as "custom", and when I removed the pre-installed PICO SDK, and built the example scene with the officially released PICO package, I found the function worked but the hand visualization was weird.

![Screenshot_com Phantom PicoMRTK3SDK214Lo_2023 05 16-17 17 45 507_685](https://github.com/Phantomxm2021/PicoMRTK3/assets/42880413/2eeb6499-b3c9-4cd4-bff8-776f1fe523fb)

I wonder if using the pre-installed PICO SDK is necessary and how I can change the SDK version on my own :)

**Comment by MuRongxuan1998** [comment]
[https://github.com/Phantomxm2021/PicoMRTK3/issues/3](url)

uhh……it's not an issue with SDK version, but XRRig configuration :)

**Comment by RongxuanMu** [comment]
[https://github.com/Phantomxm2021/PicoMRTK3/issues/3](url)

uhh……it's not an issue with SDK version, but XRRig configuration :)
