### ISSUE TITLE
The model joints identified by the hand are misaligned

### ISSUE THREAD

**Issue by renfengyi** [Phantomxm2021/PicoMRTK3#8]
Hello, I installed the latest version of the code into Pico4 after it was released. Instead of using the handle, I used gesture recognition. However, the identified joints of the hand model of the two hands were both horizontally dislocated.

**Comment by Phantomxm2021** [comment]
Provide some video or pictures for better understanding of the problem ,plz.

**Comment by michitomo** [comment]
Hi, I think I am experiencing the same situation.
https://www.youtube.com/watch?v=Yw0J0LougGU

Built on Unity 2022.3.4f1. Somehow, I was unable to build on Unity 2021. I'll try building on the right version tomorrow.

**Comment by michitomo** [comment]
It might be Pico's new firmware issue. I am reporting them.

**Comment by JurajVincur** [comment]
You are probably not using correct hand prefabs, check MRTK XR Rig -> Camera Offset -> MRTK RightHand Controller.
In script Articulated Hand Controller check field Model Prefab. Should be set to prefab that has PXR_Hand script on.

**Comment by Phantomxm2021** [comment]
Thanks. We have adapted to the new version of SDK
